x-logging-common: &logging-common
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "7"

services:
  crop.hello.infra.aspire:
    env_file: .env
    image: crop/hello/infra/aspire:${SERVICE_VERSION}
    build:
      context: .
      args:
        - SERVICE_USER=${SERVICE_USER}
        - SERVICE_UID=${SERVICE_UID}
        - SERVICE_GID=${SERVICE_GID}
      dockerfile: Backend/Build/Dockerfiles/Aspire/Dockerfile
    container_name: corp.hello.infra.aspire
    hostname: corp.hello.infra.aspire
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - 4317:18889      # OTLP/gRPC
      - 4318:18890      # OTLP/HTTP
      - 18888:18888     # http dashboard
    networks:
      - net
    logging: *logging-common

networks:
  net:
    name: crop.hello